<div class="card-header">Register Person</div>
<div class="card-body">
    <form id="store">
        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" name="name" id="name" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="email">E-mail:</label>
            <input type="text" name="email" id="email" class="form-control"pattern=".+@+.+" required>
        </div>
        <div class="form-group">
            <label for="telephone">Telephone:</label>
            <input type="text" name="telephone" id="telephone" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="birthday">Birthday:</label>
            <input type="date" name="birthday" id="birthday" class="form-control">
        </div>
        <div class="form-group">
            <label for="address">Address:</label>
            <input type="text" name="address" id="address" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
</div>

<script>

    $(document).ready(function () {
        $('#telephone').mask("(00)00000-0000", {placeholder: "(__)_____-____"});
        $('#store').on('submit', function (e) {
            e.preventDefault();
            $.ajax({
                type:'POST',
                url:'/store',
                data: $(this).serialize(),
                success: () => {
                    alert("Successfully Registered");
                    window.location.href = "/";
                }
            });
        })
    });
</script>
